# development:
#   adapter: mysql
#   encoding: utf8
#   database: min_dev
#   username: root
#   password: 
#   socket: /tmp/mysql.sock
# 
# test:
#   adapter: mysql
#   encoding: utf8
#   database: min_root
#   username: root
#   password: 
#   socket: /tmp/mysql.sock
# 
# production:
#   adapter: mysql
#   encoding: utf8
#   database: min_prod
#   username: root
#   password: 
#   socket: /tmp/mysql.sock
# 

development:
  adapter: mysql
  database: notemare_dev
  username: root
  password: 7fusjsm3j2$#(8&Unafj42*JEKN
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  database: notemare_test
  username: root
  password: 7fusjsm3j2$#(8&Unafj42*JEKN
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  database: notemare_prod
  username: root
  password: 7fusjsm3j2$#(8&Unafj42*JEKN
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
