development:
  adapter: mysql
  encoding: utf8
  database: min_dev
  username: root
  password: prodpass1!
  socket: /usr/bin/mysql

test:
  adapter: mysql
  encoding: utf8
  database: min_root
  username: root
  password: prodpass1!
  socket: /usr/bin/mysql

production:
  adapter: mysql
  encoding: utf8
  database: min_prod
  username: root
  password: prodpass1!
  socket: /usr/bin/mysql
